"""Synthetic lab fixtures shaped like Flow models.

Real client_code WDON is used so the documented example questions work.
Names, addresses, and mail are fake — not production PHI.
"""

from __future__ import annotations

from datetime import datetime

from app.flow.schemas import ClientRecord, ContactRecord, MailRecord, TechnicianRecord, TicketRecord

# Naive datetimes match Flow's DateTime columns (no timezone in MariaDB models).
_DT = datetime

CLIENTS: list[ClientRecord] = [
    ClientRecord(
        id=41,
        client_code="WDON",
        name="Western Dental",
        full_company_name="Western Dental of New Jersey (lab fixture)",
        status="Active",
        m365_default_domain="westerndental.example",
    ),
    ClientRecord(
        id=7,
        client_code="ACME",
        name="Acme Labs",
        full_company_name="Acme Laboratories (lab fixture)",
        status="Active",
        m365_default_domain="acme.example",
    ),
]

CONTACTS: list[ContactRecord] = [
    ContactRecord(
        id=101,
        client_id=41,
        client_code="WDON",
        contact_type="client",
        full_name="Debe Hernandez",
        file_as="Hernandez, Debe",
        company_name="Western Dental",
        job_title="Office Manager",
        email_1="debe@westerndental.example",
        email_2="dhernandez@westerndental.example",
        business_phone="555-0101",
        mobile_phone="555-0102",
        is_active=True,
    ),
    ContactRecord(
        id=102,
        client_id=41,
        client_code="WDON",
        contact_type="client",
        full_name="Chris Patel",
        file_as="Patel, Chris",
        company_name="Western Dental",
        job_title="Front Desk",
        email_1="cpatel@westerndental.example",
        is_active=True,
    ),
    ContactRecord(
        id=201,
        client_id=7,
        client_code="ACME",
        contact_type="client",
        full_name="Riley Chen",
        file_as="Chen, Riley",
        company_name="Acme Labs",
        email_1="riley@acme.example",
        is_active=True,
    ),
    ContactRecord(
        id=202,
        client_id=7,
        client_code="ACME",
        contact_type="client",
        full_name="Michael Sodl",
        file_as="Sodl, Michael",
        company_name="Acme Labs",
        email_1="michael@acme.example",
        is_active=True,
    ),
]

TICKETS: list[TicketRecord] = [
    TicketRecord(
        id=9001,
        client_id=41,
        client_code="WDON",
        ticket_num="1842",
        subject="|WDON|1842| {Debe Hernandez} Imaging workstation offline",
        topic="Imaging workstation offline",
        status="Open",
        category="Normal",
        requestor_text="Debe Hernandez",
        contact_id=101,
        machine_name="WDON-IMG-01",
        assignee_code="tr",
        reason="Support",
        complete=False,
        due_at=_DT(2026, 9, 1, 9, 0, 0),
        created_at=_DT(2026, 9, 17, 14, 5, 0),
        last_activity_at=_DT(2026, 9, 18, 9, 41, 0),
    ),
    TicketRecord(
        id=8990,
        client_id=41,
        client_code="WDON",
        ticket_num="1830",
        subject="|WDON|1830| {Chris Patel} Password reset",
        topic="Password reset",
        status="Closed",
        category="Normal",
        requestor_text="Chris Patel",
        contact_id=102,
        assignee_code="tr",
        complete=True,
        created_at=_DT(2026, 8, 4, 11, 0, 0),
        last_activity_at=_DT(2026, 8, 4, 11, 22, 0),
        closed_at=_DT(2026, 8, 4, 11, 22, 0),
    ),
    TicketRecord(
        id=3100,
        client_id=7,
        client_code="ACME",
        ticket_num="0041",
        subject="|ACME|0041| {Riley Chen} VPN dropouts",
        topic="VPN dropouts",
        status="Open",
        category="Normal",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="ts",
        reason="Billable/New",
        project=True,
        invoice_num="INV-441",
        job="JOB-9",
        cause="Hardware failure",
        created_at=_DT(2026, 9, 10, 8, 0, 0),
        last_activity_at=_DT(2026, 9, 19, 16, 0, 0),
    ),
    # Same client, contact, and issue as ACME-0041 — the duplicate that
    # find_similar_tickets should surface (keep 0041, absorb 0045).
    TicketRecord(
        id=3105,
        client_id=7,
        client_code="ACME",
        ticket_num="0045",
        subject="|ACME|0045| {Riley Chen} VPN dropouts again",
        topic="VPN dropouts again",
        status="New",
        category="Normal",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="ts",
        created_at=_DT(2026, 9, 19, 15, 30, 0),
        last_activity_at=_DT(2026, 9, 19, 15, 45, 0),
    ),
    TicketRecord(
        id=3110,
        client_id=7,
        client_code="ACME",
        ticket_num="0050",
        subject="|ACME|0050| {Riley Chen} VPN dropouts wrap-up",
        topic="VPN dropouts wrap-up",
        status="Done",
        category="9 REVIEW",
        stage="review",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="ts",
        complete=True,
        created_at=_DT(2026, 9, 20, 9, 0, 0),
        last_activity_at=_DT(2026, 9, 20, 9, 15, 0),
    ),
    TicketRecord(
        id=3200,
        client_id=7,
        client_code="ACME",
        ticket_num="0010",
        subject="|ACME|0010| {Riley Chen} Old VPN ticket",
        topic="Old VPN ticket",
        status="Done",
        category="9 REVIEW",
        stage="archived",
        requestor_text="Riley Chen",
        assignee_code="ts",
        complete=True,
        archived=True,
        created_at=_DT(2026, 7, 1, 9, 0, 0),
        last_activity_at=_DT(2026, 7, 2, 9, 0, 0),
        archived_at=_DT(2026, 7, 3, 9, 0, 0),
    ),
    TicketRecord(
        id=3300,
        client_id=7,
        client_code="ACME",
        ticket_num="0099",
        subject="|ACME|0099| {Riley Chen} Server down",
        topic="Server down",
        status="Open",
        category="0 Urgent",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="eo",
        created_at=_DT(2026, 9, 22, 10, 0, 0),
        last_activity_at=_DT(2026, 9, 22, 10, 15, 0),
    ),
    TicketRecord(
        id=3400,
        client_id=7,
        client_code="ACME",
        ticket_num="0400",
        subject="|ACME|0400| {Michael Sodl} VPN Unaccessible",
        topic="VPN Unaccessible",
        status="Open",
        category="Normal",
        requestor_text="Michael Sodl",
        assignee_code="dh",
        created_at=_DT(2026, 9, 23, 8, 0, 0),
        last_activity_at=_DT(2026, 9, 23, 8, 15, 0),
    ),
]

# Flow users rows (assignees), allowlisted fields only.
TECHNICIANS: list[TechnicianRecord] = [
    TechnicianRecord(
        id=1,
        display_name="Tre Seibert",
        email="tseibert@techbldrs.example",
        assignee_code="ts",
        role="administrator",
    ),
    TechnicianRecord(
        id=2,
        display_name="Tom Rivera",
        email="trivera@techbldrs.example",
        assignee_code="tr",
        role="technician",
    ),
]

MAIL: list[MailRecord] = [
    MailRecord(
        id=50001,
        ticket_id=9001,
        client_code="WDON",
        ticket_num="1842",
        direction="inbound",
        from_address="debe@westerndental.example",
        from_name="Debe Hernandez",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Scanner / imaging PC is down again",
        received_at=_DT(2026, 9, 17, 14, 22, 0),
        created_at=_DT(2026, 9, 17, 14, 23, 0),
        snippet="[Parsed Inbound] Imaging workstation WDON-IMG-01 will not boot past the login screen.",
    ),
    MailRecord(
        id=50002,
        ticket_id=9001,
        client_code="WDON",
        ticket_num="1842",
        direction="outbound",
        from_address="support@techbldrs.example",
        from_name="TechBldrs Support",
        to_label="Debe Hernandez <debe@westerndental.example>",
        subject="Re: Scanner / imaging PC is down again",
        received_at=_DT(2026, 9, 17, 15, 10, 0),
        created_at=_DT(2026, 9, 17, 15, 10, 0),
        snippet="[Sent via Graph] On-site tech scheduled tomorrow morning.",
    ),
    MailRecord(
        id=50003,
        ticket_id=9001,
        client_code="WDON",
        ticket_num="1842",
        direction="inbound",
        from_address="debe@westerndental.example",
        from_name="Debe Hernandez",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Re: Scanner / imaging PC is down again",
        received_at=_DT(2026, 9, 18, 9, 40, 0),
        created_at=_DT(2026, 9, 18, 9, 41, 0),
        snippet="[Parsed Inbound] Machine is back up. Thanks — Debe",
    ),
    MailRecord(
        id=50010,
        ticket_id=8990,
        client_code="WDON",
        ticket_num="1830",
        direction="inbound",
        from_address="cpatel@westerndental.example",
        from_name="Chris Patel",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Need a password reset",
        received_at=_DT(2026, 8, 4, 10, 55, 0),
        created_at=_DT(2026, 8, 4, 10, 56, 0),
        snippet="[Parsed Inbound] Locked out of M365.",
    ),
    MailRecord(
        id=50020,
        ticket_id=3100,
        client_code="ACME",
        ticket_num="0041",
        direction="inbound",
        from_address="riley@acme.example",
        from_name="Riley Chen",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="VPN keeps dropping",
        received_at=_DT(2026, 9, 10, 8, 5, 0),
        created_at=_DT(2026, 9, 10, 8, 6, 0),
        snippet="[Parsed Inbound] Tunnel dies after about 20 minutes.",
    ),
]
