"""Synthetic lab fixtures shaped like Flow models.

Real client_code WDON is used so the documented example questions work.
Names, addresses, and mail are fake — not production PHI.
"""

from __future__ import annotations

from datetime import datetime

from app.flow.schemas import (
    ClientRecord,
    ContactRecord,
    MachineRecord,
    MailRecord,
    TechnicianRecord,
    TicketRecord,
    TimeEntryRecord,
)

# Naive datetimes match Flow's DateTime columns (no timezone in MariaDB models).
_DT = datetime

CLIENTS: list[ClientRecord] = [
    ClientRecord(
        id=41,
        client_code="WDON",
        name="Western Dental",
        full_company_name="Western Dental of New Jersey (lab fixture)",
        status="Active",
        m365_default_domain="westerndental.example",
    ),
    ClientRecord(
        id=7,
        client_code="ACME",
        name="Acme Labs",
        full_company_name="Acme Laboratories (lab fixture)",
        status="Active",
        m365_default_domain="acme.example",
    ),
]

CONTACTS: list[ContactRecord] = [
    ContactRecord(
        id=101,
        client_id=41,
        client_code="WDON",
        contact_type="client",
        full_name="Debe Hernandez",
        file_as="Hernandez, Debe",
        company_name="Western Dental",
        job_title="Office Manager",
        email_1="debe@westerndental.example",
        email_2="dhernandez@westerndental.example",
        business_phone="555-0101",
        mobile_phone="555-0102",
        is_active=True,
    ),
    ContactRecord(
        id=102,
        client_id=41,
        client_code="WDON",
        contact_type="client",
        full_name="Chris Patel",
        file_as="Patel, Chris",
        company_name="Western Dental",
        job_title="Front Desk",
        email_1="cpatel@westerndental.example",
        is_active=True,
    ),
    ContactRecord(
        id=201,
        client_id=7,
        client_code="ACME",
        contact_type="client",
        full_name="Riley Chen",
        file_as="Chen, Riley",
        company_name="Acme Labs",
        email_1="riley@acme.example",
        is_active=True,
    ),
    ContactRecord(
        id=202,
        client_id=7,
        client_code="ACME",
        contact_type="client",
        full_name="Michael Sodl",
        file_as="Sodl, Michael",
        company_name="Acme Labs",
        email_1="michael@acme.example",
        is_active=True,
    ),
    ContactRecord(
        id=203,
        client_id=41,
        client_code="WDON",
        contact_type="client",
        full_name="Thomas Carter",
        file_as="Carter, Thomas",
        company_name="Western Dental",
        email_1="thomas.carter@westerndental.example",
        is_active=True,
    ),
    ContactRecord(
        id=204,
        client_id=41,
        client_code="WDON",
        contact_type="client",
        full_name="Sean O'Brien",
        file_as="O'Brien, Sean",
        company_name="Western Dental",
        email_1="sean.obrien@westerndental.example",
        is_active=True,
    ),
    ContactRecord(
        id=205,
        client_id=7,
        client_code="ACME",
        contact_type="client",
        full_name="April O'Brien",
        file_as="O'Brien, April",
        company_name="Acme Labs",
        email_1="april.obrien@acme.example",
        is_active=True,
    ),
]

TICKETS: list[TicketRecord] = [
    TicketRecord(
        id=9001,
        client_id=41,
        client_code="WDON",
        ticket_num="1842",
        subject="|WDON|1842| {Debe Hernandez} Imaging workstation offline",
        topic="Imaging workstation offline",
        status="Open",
        category="Normal",
        requestor_text="Debe Hernandez",
        contact_id=101,
        machine_name="WDON-IMG-01",
        assignee_code="tr",
        reason="Support",
        complete=False,
        due_at=_DT(2026, 9, 1, 9, 0, 0),
        created_at=_DT(2026, 9, 17, 14, 5, 0),
        last_activity_at=_DT(2026, 9, 18, 9, 41, 0),
    ),
    TicketRecord(
        id=8990,
        client_id=41,
        client_code="WDON",
        ticket_num="1830",
        subject="|WDON|1830| {Chris Patel} Password reset",
        topic="Password reset",
        status="Closed",
        category="Normal",
        requestor_text="Chris Patel",
        contact_id=102,
        assignee_code="tr",
        complete=True,
        created_at=_DT(2026, 8, 4, 11, 0, 0),
        last_activity_at=_DT(2026, 8, 4, 11, 22, 0),
        closed_at=_DT(2026, 8, 4, 11, 22, 0),
    ),
    TicketRecord(
        id=3100,
        client_id=7,
        client_code="ACME",
        ticket_num="0041",
        subject="|ACME|0041| {Riley Chen} VPN dropouts",
        topic="VPN dropouts",
        status="Open",
        category="Normal",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="ts",
        reason="Billable/New",
        project=True,
        invoice_num="INV-441",
        job="JOB-9",
        cause="Hardware failure",
        created_at=_DT(2026, 9, 10, 8, 0, 0),
        last_activity_at=_DT(2026, 9, 19, 16, 0, 0),
    ),
    # Same client, contact, and issue as ACME-0041 — the duplicate that
    # find_similar_tickets should surface (keep 0041, absorb 0045).
    TicketRecord(
        id=3105,
        client_id=7,
        client_code="ACME",
        ticket_num="0045",
        subject="|ACME|0045| {Riley Chen} VPN dropouts again",
        topic="VPN dropouts again",
        status="New",
        category="Normal",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="ts",
        created_at=_DT(2026, 9, 19, 15, 30, 0),
        last_activity_at=_DT(2026, 9, 19, 15, 45, 0),
    ),
    TicketRecord(
        id=3110,
        client_id=7,
        client_code="ACME",
        ticket_num="0050",
        subject="|ACME|0050| {Riley Chen} VPN dropouts wrap-up",
        topic="VPN dropouts wrap-up",
        status="Done",
        category="9 REVIEW",
        stage="review",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="ts",
        complete=True,
        created_at=_DT(2026, 9, 20, 9, 0, 0),
        last_activity_at=_DT(2026, 9, 20, 9, 15, 0),
    ),
    TicketRecord(
        id=3200,
        client_id=7,
        client_code="ACME",
        ticket_num="0010",
        subject="|ACME|0010| {Riley Chen} Old VPN ticket",
        topic="Old VPN ticket",
        status="Done",
        category="9 REVIEW",
        stage="archived",
        requestor_text="Riley Chen",
        assignee_code="ts",
        complete=True,
        archived=True,
        created_at=_DT(2026, 7, 1, 9, 0, 0),
        last_activity_at=_DT(2026, 7, 2, 9, 0, 0),
        archived_at=_DT(2026, 7, 3, 9, 0, 0),
    ),
    TicketRecord(
        id=3300,
        client_id=7,
        client_code="ACME",
        ticket_num="0099",
        subject="|ACME|0099| {Riley Chen} Server down",
        topic="Server down",
        status="Open",
        category="0 Urgent",
        requestor_text="Riley Chen",
        contact_id=201,
        assignee_code="eo",
        created_at=_DT(2026, 9, 22, 10, 0, 0),
        last_activity_at=_DT(2026, 9, 22, 10, 15, 0),
    ),
    TicketRecord(
        id=3400,
        client_id=7,
        client_code="ACME",
        ticket_num="0400",
        subject="|ACME|0400| {Michael Sodl} VPN Unaccessible",
        topic="VPN Unaccessible",
        status="Open",
        category="Normal",
        requestor_text="Michael Sodl",
        assignee_code="dh",
        created_at=_DT(2026, 9, 23, 8, 0, 0),
        last_activity_at=_DT(2026, 9, 23, 8, 15, 0),
    ),
    TicketRecord(
        id=2619,
        client_id=41,
        client_code="WDON",
        ticket_num="2619",
        subject="|WDON|2619| {Thomas Carter} B Ellerby Email",
        topic="B Ellerby Email",
        status="Open",
        category="2 Normal",
        requestor_text="Thomas Carter",
        assignee_code="dh",
        created_at=_DT(2026, 9, 25, 12, 50, 0),
        last_activity_at=_DT(2026, 9, 25, 12, 57, 0),
    ),
    # Requestor only — no contact_id. A shared last name must not steal this row.
    TicketRecord(
        id=2621,
        client_id=41,
        client_code="WDON",
        ticket_num="2621",
        subject="|WDON|2621| {Sean O'Brien} Create Payroll Email Address",
        topic="Create Payroll Email Address",
        status="Open",
        category="2 Normal",
        requestor_text="Sean O'Brien",
        assignee_code="dh",
        created_at=_DT(2026, 9, 10, 7, 44, 0),
        last_activity_at=_DT(2026, 9, 10, 7, 44, 0),
    ),
    TicketRecord(
        id=2622,
        client_id=41,
        client_code="WDON",
        ticket_num="2622",
        subject="|WDON|2622| Sean O'Brien asked Chris about payroll",
        topic="Sean O'Brien asked about payroll",
        status="Open",
        category="2 Normal",
        requestor_text="Chris Patel",
        contact_id=102,
        assignee_code="dh",
        created_at=_DT(2026, 9, 12, 8, 30, 0),
        last_activity_at=_DT(2026, 9, 12, 8, 30, 0),
    ),
    TicketRecord(
        id=2700,
        client_id=7,
        client_code="ACME",
        ticket_num="0700",
        subject="|ACME|0700| {April O'Brien} Badge printer",
        topic="Badge printer",
        status="Open",
        category="2 Normal",
        requestor_text="April O'Brien",
        contact_id=205,
        assignee_code="dh",
        archived=True,
        created_at=_DT(2026, 9, 11, 8, 0, 0),
        last_activity_at=_DT(2026, 9, 11, 8, 5, 0),
        archived_at=_DT(2026, 9, 11, 9, 0, 0),
    ),
    # A catch-all bucket ticket, not a real single piece of work -- the case
    # answer_longest_time_worked must exclude even though its hours dwarf everything else.
    TicketRecord(
        id=9999,
        client_id=7,
        client_code="ZTB",
        ticket_num="0006",
        subject="|ZTB|0006| Meetings",
        topic="Meetings",
        status="New",
        category="Place Holder",
        reason="Internal",
        requestor_text="",
        created_at=_DT(2024, 1, 1, 8, 0, 0),
        last_activity_at=_DT(2026, 9, 29, 8, 0, 0),
        hrs_actual_total=559.53,
    ),
]

# Flow users rows (assignees), allowlisted fields only.
TECHNICIANS: list[TechnicianRecord] = [
    TechnicianRecord(
        id=1,
        display_name="Tre Seibert",
        email="tseibert@techbldrs.example",
        assignee_code="ts",
        role="administrator",
    ),
    TechnicianRecord(
        id=2,
        display_name="Tom Rivera",
        email="trivera@techbldrs.example",
        assignee_code="tr",
        role="technician",
    ),
]

MAIL: list[MailRecord] = [
    MailRecord(
        id=50001,
        ticket_id=9001,
        client_code="WDON",
        ticket_num="1842",
        direction="inbound",
        from_address="debe@westerndental.example",
        from_name="Debe Hernandez",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Scanner / imaging PC is down again",
        received_at=_DT(2026, 9, 17, 14, 22, 0),
        created_at=_DT(2026, 9, 17, 14, 23, 0),
        snippet="[Parsed Inbound] Imaging workstation WDON-IMG-01 will not boot past the login screen.",
    ),
    MailRecord(
        id=50002,
        ticket_id=9001,
        client_code="WDON",
        ticket_num="1842",
        direction="outbound",
        from_address="support@techbldrs.example",
        from_name="TechBldrs Support",
        to_label="Debe Hernandez <debe@westerndental.example>",
        subject="Re: Scanner / imaging PC is down again",
        received_at=_DT(2026, 9, 17, 15, 10, 0),
        created_at=_DT(2026, 9, 17, 15, 10, 0),
        snippet="[Sent via Graph] On-site tech scheduled tomorrow morning.",
    ),
    MailRecord(
        id=50003,
        ticket_id=9001,
        client_code="WDON",
        ticket_num="1842",
        direction="inbound",
        from_address="debe@westerndental.example",
        from_name="Debe Hernandez",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Re: Scanner / imaging PC is down again",
        received_at=_DT(2026, 9, 18, 9, 40, 0),
        created_at=_DT(2026, 9, 18, 9, 41, 0),
        snippet="[Parsed Inbound] Machine is back up. Thanks — Debe",
    ),
    MailRecord(
        id=50010,
        ticket_id=8990,
        client_code="WDON",
        ticket_num="1830",
        direction="inbound",
        from_address="cpatel@westerndental.example",
        from_name="Chris Patel",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Need a password reset",
        received_at=_DT(2026, 8, 4, 10, 55, 0),
        created_at=_DT(2026, 8, 4, 10, 56, 0),
        snippet="[Parsed Inbound] Locked out of M365.",
    ),
    MailRecord(
        id=50020,
        ticket_id=3100,
        client_code="ACME",
        ticket_num="0041",
        direction="inbound",
        from_address="riley@acme.example",
        from_name="Riley Chen",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="VPN keeps dropping",
        received_at=_DT(2026, 9, 10, 8, 5, 0),
        created_at=_DT(2026, 9, 10, 8, 6, 0),
        snippet="[Parsed Inbound] Tunnel dies after about 20 minutes.",
    ),
    MailRecord(
        id=50030,
        ticket_id=2621,
        client_code="WDON",
        ticket_num="2621",
        direction="inbound",
        from_address="sean.obrien@westerndental.example",
        from_name="Sean O'Brien",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Create Payroll Email Address",
        received_at=_DT(2026, 9, 10, 7, 44, 0),
        created_at=_DT(2026, 9, 10, 7, 44, 0),
        snippet="[Parsed Inbound] Need a payroll mailbox set up today.",
    ),
    MailRecord(
        id=50031,
        ticket_id=2622,
        client_code="WDON",
        ticket_num="2622",
        direction="inbound",
        from_address="cpatel@westerndental.example",
        from_name="Chris Patel",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Sean O'Brien asked about payroll",
        received_at=_DT(2026, 9, 12, 8, 30, 0),
        created_at=_DT(2026, 9, 12, 8, 30, 0),
        snippet="[Parsed Inbound] Sean mentioned payroll but this mail is from Chris.",
    ),
    MailRecord(
        id=50032,
        ticket_id=2700,
        client_code="ACME",
        ticket_num="0700",
        direction="inbound",
        from_address="april.obrien@acme.example",
        from_name="April O'Brien",
        to_label="TechBldrs Support <support@techbldrs.example>",
        subject="Badge printer jam",
        received_at=_DT(2026, 9, 11, 8, 5, 0),
        created_at=_DT(2026, 9, 11, 8, 5, 0),
        snippet="[Parsed Inbound] Newer mail from a different O'Brien.",
    ),
]

# tech_user_id 1 = ts (Tre Seibert), 2 = tr (Tom Rivera) — matches TECHNICIANS ids above.
TIME_ENTRIES: list[TimeEntryRecord] = [
    TimeEntryRecord(
        id=70001,
        ticket_id=9001,
        client_code="WDON",
        ticket_num="1842",
        tech_user_id=2,
        start_at=_DT(2026, 9, 18, 9, 0, 0),
        end_at=_DT(2026, 9, 18, 9, 41, 0),
        bill_start_at=_DT(2026, 9, 18, 9, 0, 0),
        bill_end_at=_DT(2026, 9, 18, 9, 45, 0),
        work_date=_DT(2026, 9, 18, 0, 0, 0),
        actual_minutes=41,
        minutes=45,
        subject="On-site: imaging workstation repair",
        body="Replaced failed boot drive on WDON-IMG-01 and restored image.",
        billable=True,
        reviewed=True,
        invoice_desc="WDON imaging repair",
        created_at=_DT(2026, 9, 18, 9, 45, 0),
    ),
    TimeEntryRecord(
        id=70002,
        ticket_id=3100,
        client_code="ACME",
        ticket_num="0041",
        tech_user_id=1,
        start_at=_DT(2026, 9, 19, 16, 0, 0),
        end_at=_DT(2026, 9, 19, 16, 20, 0),
        bill_start_at=_DT(2026, 9, 19, 16, 0, 0),
        bill_end_at=_DT(2026, 9, 19, 16, 30, 0),
        work_date=_DT(2026, 9, 19, 0, 0, 0),
        actual_minutes=20,
        minutes=30,
        subject="Remote: VPN tunnel troubleshooting",
        body="Checked firewall logs; tunnel drops correlate with DHCP lease renewal.",
        billable=True,
        job="JOB-9",
        invoice_num="INV-441",
        invoice_desc="ACME VPN troubleshooting",
        activity_tags=["network_vpn"],
        created_at=_DT(2026, 9, 19, 16, 30, 0),
    ),
]

MACHINES: list[MachineRecord] = [
    MachineRecord(
        id=80001,
        client_id=41,
        client_code="WDON",
        machine_name="WDON-IMG-01",
        machine_support="Managed",
        source="datto",
        web_remote_url="https://remote.example/wdon-img-01",
        last_seen_at=_DT(2026, 9, 18, 9, 0, 0),
        created_at=_DT(2026, 1, 5, 0, 0, 0),
    ),
    MachineRecord(
        id=80002,
        client_id=41,
        client_code="WDON",
        machine_name="WDON-FS-01",
        machine_support="Managed",
        source="datto",
        last_seen_at=_DT(2026, 9, 20, 6, 0, 0),
        created_at=_DT(2026, 1, 5, 0, 0, 0),
    ),
    MachineRecord(
        id=80010,
        client_id=7,
        client_code="ACME",
        machine_name="ACME-WKS-14",
        machine_support="Managed",
        source="datto",
        last_seen_at=_DT(2026, 9, 22, 7, 0, 0),
        created_at=_DT(2026, 2, 1, 0, 0, 0),
    ),
]

# Extra detail-only fields for get_ticket/get_mail/get_client, keyed by id/code.
# Rows not listed here fall back to the base record + None/blank detail fields.
TICKET_DETAIL_EXTRAS: dict[int, dict] = {
    9001: {
        "hrs_actual_total": 0.75,
        "hrs_billable_total": 0.75,
        "hrs_gratis_total": 0.0,
        "log_text": (
            "2026-09-17 14:05 Ticket opened by Debe Hernandez.\n"
            "2026-09-18 09:41 On-site repair completed, boot drive replaced."
        ),
        "notes_text": "Recurring boot failures on this workstation; consider replacement.",
        "assignee_user_id": 2,
    },
}

MAIL_DETAIL_EXTRAS: dict[int, dict] = {
    50003: {"body": "Machine is back up. Thanks — Debe", "importance": "normal"},
}

CLIENT_DETAIL_EXTRAS: dict[str, dict] = {
    "WDON": {"contract_minutes": 600, "balance": 120, "account": "Managed Services"},
}
